import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{
            padding: 12,
            borderBottom: "1px solid #e5e5e5",
            display: "flex",
            gap: 16,
          }}
        >
          <a href="/login">Login</a>
          <a href="/register">Register</a>
          <a href="/hives">Hives</a>
        </nav>

        {children}
      </body>
    </html>
  );
}
